# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: python-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'CI Tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run CI'
        type: environment
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install black pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Modify Files using Current Branch Name
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          # Find and update Python files with Jinja pattern
          find . -type f -name "*.py" -exec sh -c '
            for file do
              # Replace {{ git_branch }} with the current branch name
              sed -i "s/{{ git_branch }}/$GITHUB_REF_NAME/g" "$file"
            done
          ' sh {} +
        fi
    - name: Handle Versioning
      uses: google-github-actions/release-please-action@v3
      with:
        release-type: python
        package-name: release-please-action
    - name: Auto Lint with black, pylint
      run: |
        black .
        black --diff --check $(git ls-files '*.py')
        pylint --disable=all --enable=unused-import $(git ls-files '*.py')
    - name: Push Linting and Versioning Changes
      run: |
        # Commit the changes
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "chore(versioning): versioning and linting changes"

        # Push the changes back to the branch
        git push